### ISSUE TITLE
Service is stuck

### ISSUE THREAD

**Issue by Farmer94** [MathiasHun/FS25_Real_Vehicle_Breakdowns_Beta#28]
I have a problem, the script hangs. It tells me that the vehicle will be ready at 7:30 a.m. As soon as this time is over, the same thing happens again. no matter whether real time or in-game time.
No matter whether mod vehicles or from giants.

**Comment by MathiasHun** [comment]
SP or MP? log file? I don't experience this issue.

**Comment by MathiasHun** [comment]
Fixed?

**Comment by GRYPHUS-01** [comment]
i have this currently ongoing, not using vacation mod. Happens in Singleplayer, trying to get more data...

**Comment by MathiasHun** [comment]
Version 0.9.2.9 is already available, and a bigger update for the mod will be released soon.

**Comment by GRYPHUS-01** [comment]
After updating to V0.9.2.9, the script still hangs and the vehicle is still locked on a infinite service-in-progress.

Adding latest log but i didnt see any usefull data in it (nothing of relevance): 

[log.txt](https://github.com/user-attachments/files/22584127/log.txt)

**Comment by GRYPHUS-01** [comment]
even towing it out doesnt seem to break the script (not based on range to a workshop point it seems)
